# Site settings
baseurl = ""
languageCode = "en-us"
title = "TOP 100 PRIVATE CANNABIS COMPANIES"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-138720626-1"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "TOP 100 PRIVATE CANNABIS COMPANIES 2018"
    subtitle = ""
    author = "CANNAHARIS"
    description = ""
    keywords = "private, cannabis, companies, business"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Web Link"

    # Footer text
    footertext = "Made by [Cannabis Analyst](http://tympanus.net/codrops/2013/03/19/thumbnail-grid-with-expanding-preview/)"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
