# Site settings
baseurl = ""
languageCode = "en-us"
title = "TOP 100 PRIVATE CANNABIS COMPANIES"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-138720626-1"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "TOP 100 PRIVATE CANNABIS COMPANIES 2018"
    subtitle = "The list comprises privately held companies, primarily U.S. companies."
    author = "CANNAHARIS"
    description = "Determination to include companies on the list is subjective, and the list is intended to be a cross-section of the types of companies in the cannabis industry. Most companies on this list are in early stages of development, and many will need to raise capital to succeed."
    keywords = "private, cannabis, companies, business"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Web Link"

    # Footer text
    footertext = "Made by [Cannabis Analyst](https://www.cannabisanalyst.org)"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
